# Generated by Django 5.1.3 on 2024-11-14 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit_time',
            field=models.TimeField(default=datetime.time(21, 20, 54, 54754), help_text='Время, когда необходимо выполнять привычку', verbose_name='Время'),
        ),
    ]
