# Generated by Django 5.1.3 on 2024-11-15 18:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_habit_time_alter_habit_lead_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit_time',
            field=models.TimeField(default=django.utils.timezone.localtime, help_text='Время, когда необходимо выполнять привычку', verbose_name='Время'),
        ),
    ]
