# Generated by Django 5.1.3 on 2024-11-15 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_habit_habit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit_time',
            field=models.TimeField(default=datetime.time(18, 45, 5, 960916), help_text='Время, когда необходимо выполнять привычку', verbose_name='Время'),
        ),
    ]
