# Generated by Django 5.1.3 on 2024-11-16 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_alter_habit_habit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit_time',
            field=models.TimeField(default=datetime.time(19, 24, 36, 440256), help_text='Время, когда необходимо выполнять привычку', verbose_name='Время'),
        ),
    ]
