# Generated by Django 5.1.3 on 2024-11-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0010_alter_habit_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit_time',
            field=models.TimeField(help_text='Время, когда необходимо выполнять привычку', verbose_name='Время'),
        ),
    ]
