# Generated by Django 5.1.3 on 2024-11-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0011_alter_habit_habit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='place',
            field=models.CharField(help_text='Место, в котором необходимо выполнять привычку', max_length=150, verbose_name='Место'),
        ),
    ]
