# Generated by Django 5.1.3 on 2024-11-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0012_alter_habit_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='habit_start',
            field=models.DateField(blank=True, help_text='Укажите дату начала вырабатывания привычки', null=True, verbose_name='Дата начала работы с привычкой'),
        ),
    ]
