# Generated by Django 5.1.3 on 2024-11-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0014_alter_habit_habit_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='is_reminder_send',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Флаг, что напоминание отправлено'),
        ),
    ]
