# Generated by Django 5.1.3 on 2024-11-25 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0015_habit_is_reminder_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit_start',
            field=models.DateField(blank=True, default=datetime.date(2024, 11, 25), help_text='Укажите дату начала вырабатывания привычки', null=True, verbose_name='Дата начала работы с привычкой'),
        ),
    ]
